### ISSUE TITLE
Mailbox uses Clash's background texture, which was mistakenly placed into the Pandora pack

### ISSUE THREAD

**Issue by toontownlpz** [toonjoey/toontown-project-bikehorn#1]
![image](https://user-images.githubusercontent.com/11021224/137559152-1b0317c5-64b0-4508-b11a-3520ceb2f12a.png)

Clash turned Mickey's shoes blue to hide the fact that it's a Disney character holding the box.

**Comment by toonjoey** [comment]
You're right. Thank you so much for pointing that out! I'll notify you when it's fixed.

**Comment by toonjoey** [comment]
Fixed in 7f839c8
