### ISSUE TITLE
toon hq walls have red and green lines

### ISSUE THREAD

**Issue by hunterboppen** [toonjoey/toontown-project-bikehorn#10]
![image](https://user-images.githubusercontent.com/36281072/173019250-89509f03-8d5d-48b0-96f6-dbe308e4d7ad.png)

**Comment by GracieLovelight** [comment]
That's very interesting! I actually haven't noticed that!

**Comment by toonjoey** [comment]
![int_wall](https://user-images.githubusercontent.com/19507339/173040203-637799bf-306a-4e1a-b377-2ec636843b9a.png)
This is on the original texture, it's never shown in game due to compression.
