### ISSUE TITLE
HD Laff Meter

### ISSUE THREAD

**Issue by hauntingly** [toonjoey/toontown-project-bikehorn#15]
I just found this pack and learned about how you can use packs in TTR and oh my god! It's amazing. No issue at all was just wondering if there's an HD Laff Meter pack that goes with this or possibly an update to the Laff Meter image as it's still low quality compared to everything else. Again, this looks great in 1440p! Awesome pack.

Do you have a discord server for this project by chance?

**Comment by toonjoey** [comment]
Glad to hear you enjoy it!

Sadly the Laff Meter (and a lot of textures in Spotify) are as high quality as they can get, which sometimes means they're no better than the versions seen in the original textures. I don't know of any HD Laff Meter packs that would be compatible with Bikehorn, sadly.

No Discord server for the project (nor do I really intend to make one...the project's more or less complete now, so if I ever do make a Discord it wont be related to Bikehorn), but I have a Discord account which shares the same username as my GitHub.
