### ISSUE TITLE
Fix for TTR Under New Management update?

### ISSUE THREAD

**Issue by Wizeguy400** [toonjoey/toontown-project-bikehorn#16]
I know you said you're taking a break from this pack, but I was testing this content pack on TTR's Under New Management update playtest server, and I noticed they edited the cog HQ pallettes. Most of them actually add the HD pandora textures by default, but there's a few textures that are still low quality. Whenever the update releases on the live server, any chance you could try to fix the pallettes?

**Comment by toonjoey** [comment]
I will need to update this when it comes time, yes. Keeping this open for further discussion/a reminder.

**Comment by toonjoey** [comment]
(Also to clarify, the break's technically up but I just haven't found anything I really need to do here anymore, unless I wanted to redo the entire pack from scratch for 5 pixels of better quality.)

**Comment by toonjoey** [comment]
Figured I should mention for the sake of transparency, the next release will drop whenever Under New Management does. Looked at the phases myself and it seems very simple to convert the pack off of the old stuff and onto the new, plus will help me beat the initial surge of crowds that will inevitably cause the servers to go boom.

**Comment by toonjoey** [comment]
> the next release will drop whenever Under New Management does.

Oops.
It will drop as soon as I'm home.

**Comment by toonjoey** [comment]
And now that Under New Management compatibility is added in full (and now with assets higher quality than palettes could ever dream of!), I can consider this closed.
