### ISSUE TITLE
Donald's Dreamland Clouds transparency issue

### ISSUE THREAD

**Issue by MrCheeze446** [toonjoey/toontown-project-bikehorn#4]
![image](https://user-images.githubusercontent.com/30207076/143965241-dbc649eb-ec59-4d05-adb2-4910a24a0e5e.png)
Probably something with an RGB file not being upscaled to fit the texture

**Comment by toonjoey** [comment]
This seems to be on the original texture, so I'm keeping it for now. Might try to clean it up later though.
![test_clouds](https://user-images.githubusercontent.com/19507339/144000255-c1dd77b1-ee71-460b-b114-5c921b7fc359.png)

**Comment by MrCheeze446** [comment]
![image](https://user-images.githubusercontent.com/30207076/144065278-f37717c6-b21d-42eb-970b-43ed9a2bc2a7.png)
This is how it looks in-game with the original texture, it's either just not there or much less noticeable due to the compression.

**Comment by toonjoey** [comment]
Yeah, it's just really compressed.
If you squint your eyes you can still just about see it.
![image](https://user-images.githubusercontent.com/19507339/144081185-c51d0ce4-17a4-465a-9f18-c5df29f33f62.png)
I'll probably clean it up sometime.
