### ISSUE TITLE
Paper for rollodex attack uses RGB for the texture

### ISSUE THREAD

**Issue by MrCheeze446** [toonjoey/toontown-project-bikehorn#5]
same story as the golf club I mentioned a while back

**Comment by toonjoey** [comment]
Sorry for not looking at this sooner, was taking a short break from Toontown content.

Would you mind telling me the filename for the roll-o-dex texture? I've been trying to look for it but can't seem to find it (in phase 5 at least).

**Comment by MrCheeze446** [comment]
uhhhh I'm not entirely sure, I can search around and try to find it

**Comment by MrCheeze446** [comment]
I found the texture it's battle_props_palette_1lmla_1.jpg, it's not using an RGB however it is pure white for some reason in the pack. I don't really know why this is the case, the game is clearly seeing that this file exists but isn't applying its texture properly.  

Bit of a correction, this palette seems to be for the model itself but not the particle itself(?)

**Comment by toonjoey** [comment]
Fixed as of [c0df0e7](https://github.com/toonjoey/toontown-project-bikehorn/commit/c0df0e71f96c3884fdf7a70e52e1bd31bae76a71)
