### ISSUE TITLE
Suggestion: Remove unused TTO textures and repeat TTR textures (such as their BBHQ and crash cashbot resources)

### ISSUE THREAD

**Issue by MrCheeze446** [toonjoey/toontown-project-bikehorn#7]
- classic char textures (phase_3 & phase_6)
- a few TTR BBHQ resources in phase_12
- crash cashbot resources in phase_10
- cogdominium textures in phase_5 (including the unused LBFO textures)
- TTR accessories in phase_4 
- TTR trolley game textures also in phase_4 (things such as the cog emblems andwhatever ttr_t_gui_gen_bouncyBallGUI.jpg stuff is)
- battle GUI textures because TTR replaced them and the ones in bikehorn currently are not any higher in resolution
- a lot of the gameGUI textures are just the same as the ones currently in TTR
- inGameNews_gui is unused and can be removed from phase_3.5
- anything related to TTR silly meter in phase_3.5
- unused suit pallets
- cashbot and sellbot rental suits 
- deer and croc textures from phase_3, along with he TTR chat bubbles also in phase_3

and most importantly, why? Well, this is not at all necessary but it would cut off a couple of gigs and generally just make the project probably nicer to work on.

**Comment by toonjoey** [comment]
d5f6f2e, d5f6f2e

I wont be deleting most of these since I have a small hope that higher quality sources exist and will probably be released somehow, but I think some of these can go since theres a good chance TTR wont use/change them (and in the case of the News stuff the sources we have already are at their maximum quality).

**Comment by MrCheeze446** [comment]
why keep them around of there isn't a higher version now though? it just makes things more messy, you can always just add new textures if ever found

**Comment by toonjoey** [comment]
Fair point. I'll throw them out when I get more time to work on the pack.
