### ISSUE TITLE
Estate Music is missing

### ISSUE THREAD

**Issue by GracieLovelight** [toonjoey/toontown-project-bikehorn#8]
Since Toontown Rewritten has the ability to add estate music as seen in the Toontown Infinite Music Pack for TTR and TTCC, it would be nice to see the return of the Estate music in this pack!

**Comment by toonjoey** [comment]
I'm planning on putting this out as a separate pack (which was finished forever ago, just need to figure out where to host it).

**Comment by GracieLovelight** [comment]
Why not put it on GitHub?
