### ISSUE TITLE
Low-Quality Door Textures

### ISSUE THREAD

**Issue by GracieLovelight** [toonjoey/toontown-project-bikehorn#9]
The following places have low-quality door textures:

- Toontown Central Playground Exterior Doors: ![ttr-screenshot-Sat-May-28-21-26-47-2022-18923](https://user-images.githubusercontent.com/68795576/170848173-394ee8c8-75d0-404a-b5fd-03213e97148b.png)
- Toontown Central Playground Interior Doors: ![ttr-screenshot-Sat-May-28-21-26-35-2022-18298](https://user-images.githubusercontent.com/68795576/170848174-90a29d9d-ff54-4a82-929a-7b4adbdf09e2.png)
- Toontown Central Street Exterior Doors: ![ttr-screenshot-Sat-May-28-21-27-53-2022-22424](https://user-images.githubusercontent.com/68795576/170848215-caa3ee19-8dbe-4917-a437-b480f067553f.png), ![ttr-screenshot-Sat-May-28-21-28-23-2022-24159](https://user-images.githubusercontent.com/68795576/170848224-9f98a6dd-42ef-4d14-92a1-74370d7420bb.png)
- Daisy Gardens Playground Gag Shop Exterior Doors: ![ttr-screenshot-Sat-May-28-21-30-21-2022-30974](https://user-images.githubusercontent.com/68795576/170848290-d89f8ed5-28f2-4d1b-873e-e1a45fbae5d1.png)
- Daisy Gardens Playground Doodle Shop Exterior Doors: ![ttr-screenshot-Sat-May-28-21-30-51-2022-32752](https://user-images.githubusercontent.com/68795576/170848297-3cd36493-ef05-40fb-ba22-a0e9db87312c.png)
- Daisy Gardens Street Exterior Doors: ![ttr-screenshot-Sat-May-28-21-32-23-2022-38143]
![ttr-screenshot-Sat-May-28-21-32-10-2022-37359](https://user-images.githubusercontent.com/68795576/170848326-f0958f6e-2889-4793-b472-c11e28ee6c87.png), ![ttr-screenshot-Sat-May-28-21-31-49-2022-36098](https://user-images.githubusercontent.com/68795576/170848327-6331ca81-7a74-4eb2-98e4-674dce3cb7fb.png), (https://user-images.githubusercontent.com/68795576/170848324-4c122155-7cfc-415c-a862-431a31cffa65.png), ![ttr-screenshot-Sat-May-28-21-32-16-2022-37706](https://user-images.githubusercontent.com/68795576/170848325-5b711553-5f2a-4488-886e-4acbe32b6d61.png)
- Minnie's Melodyland Gag Shop Exterior Door: ![ttr-screenshot-Sat-May-28-21-33-38-2022-42504](https://user-images.githubusercontent.com/68795576/170848364-d85bbeff-3d1b-432d-afa4-df84fb46079f.png)
- Minnie's Melodyland Pet Shop Exterior: ![ttr-screenshot-Sat-May-28-21-34-04-2022-44036](https://user-images.githubusercontent.com/68795576/170848371-61294e8e-308e-4d40-a135-1e771718b528.png)
- Minnie's Melodyland Street Exteriors: ![ttr-screenshot-Sat-May-28-21-35-38-2022-49575](ht0tps://user-images.githubusercontent.com/68795576/170848398-26c1566d-effe-4c41-abbf-1e0ee1d0fd7c.png), ![ttr-screenshot-Sat-May-28-21-35-32-2022-49225](https://user-images.githubusercontent.com/68795576/170848399-e1fe68b7-c2b7-474a-9a00-3f8bdd4563e3.png), ![ttr-screenshot-Sat-May-28-21-35-27-2022-48902](https://user-images.githubusercontent.com/68795576/170848400-10f70781-6d2f-403e-9bfb-6b1ca060bedb.png), ![ttr-screenshot-Sat-May-28-21-35-07-2022-47702](https://user-images.githubusercontent.com/68795576/170848401-483963d1-4c3c-4ceb-8d8b-3f12b98ae41c.png), ![ttr-screenshot-Sat-May-28-21-35-56-2022-50595](https://user-images.githubusercontent.com/68795576/170848409-3bc94211-e81d-49a7-9999-1fce366851c6.png)
- The Brrrgh Gag Shop Exterior: ![ttr-screenshot-Sat-May-28-21-36-58-2022-54184](https://user-images.githubusercontent.com/68795576/170848431-ab59d170-25ae-4cd9-93c0-96496c95842e.png)
- The Brrrgh Street Exteriors: ![ttr-screenshot-Sat-May-28-21-37-52-2022-57225](https://user-images.githubusercontent.com/68795576/170848466-34f121f0-9dd1-4204-bdee-eb29dc94b6a4.png), ![ttr-screenshot-Sat-May-28-21-37-41-2022-56568](https://user-images.githubusercontent.com/68795576/170848468-f8d708fb-798a-48ff-9b12-d59fd8765629.png), ![ttr-screenshot-Sat-May-28-21-37-38-2022-56397](https://user-images.githubusercontent.com/68795576/170848469-3131b663-bf3d-41be-ab27-5605cac30f68.png), ![ttr-screenshot-Sat-May-28-21-37-35-2022-56252](https://user-images.githubusercontent.com/68795576/170848470-c61cfcef-eabc-41f3-9390-02d44f7d7b97.png), ![ttr-screenshot-Sat-May-28-21-37-29-2022-55911](https://user-images.githubusercontent.com/68795576/170848472-2df59c3c-4a22-40a1-b7d9-2736eb173ef4.png)
- Donald's Dreamland Exteriors: ![ttr-screenshot-Sat-May-28-21-40-15-2022-65532](https://user-images.githubusercontent.com/68795576/170848527-85ef3b70-64df-4f72-bb4a-a7db4a2916af.png) & ![ttr-screenshot-Sat-May-28-21-40-43-2022-67182](https://user-images.githubusercontent.com/68795576/170848526-28222b26-d6c7-4019-b816-69236301098f.png)

Miscellaneous Low Quality Textures

- The Friend Button
- The X, Hand, Toons, and Arrow Buttons in the Friends List
- The Cog Disguise Parts
- The Gift Box in the Shticker Book's Options & Codes Page
- And probably more

Other than that, you've done an amazing job with restoring the uncompressed textures to Toontown Rewritten!

**Comment by toonjoey** [comment]
None of these can be fixed or improved in any significant way (I've actually tried some of these before, and they turned out lower quality in some cases).

I'll see about trying again (I think I might be misremembering the results--I know for sure doors were actually around the same quality or maybe lower) but for now they're as good as they'll be.

**Comment by GracieLovelight** [comment]
Alrighty! Thanks for trying!
